spring:
  application:
    name: catchtable

  datasource:
    url: jdbc:mysql://localhost:3306/catchtable
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8080
